// Design tokens live in packages/ui/tokens/tokens.css and are owned by the design
// system. The stylesheet imports them unconditionally, so a fresh clone (or a
// checkout made before the tokens land) would fail to compile CSS. This creates a
// minimal, clearly-marked stand-in *only when the file is missing* — it never
// overwrites real tokens. Runs from `postinstall`.
import { mkdir, writeFile, access } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const tokensFile = join(repoRoot, "packages", "ui", "tokens", "tokens.css")

const PLACEHOLDER = `/* Placeholder tokens — replaced by packages/ui/tokens as the design system lands.
   Generated by scripts/ensure-tokens.mjs because the real file was absent. */
@theme inline {
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
}
`

try {
  await access(tokensFile)
} catch {
  await mkdir(dirname(tokensFile), { recursive: true })
  await writeFile(tokensFile, PLACEHOLDER, "utf8")
  console.log("[ensure-tokens] wrote placeholder packages/ui/tokens/tokens.css")
}
