import js from "@eslint/js"
import nextPlugin from "@next/eslint-plugin-next"
import importPlugin from "eslint-plugin-import"
import reactHooks from "eslint-plugin-react-hooks"
import globals from "globals"
import tseslint from "typescript-eslint"

/** Paths no linter should ever walk. */
const IGNORED = [
  "**/node_modules/**",
  "**/.next/**",
  "**/.turbo/**",
  "**/dist/**",
  "**/coverage/**",
  "**/playwright-report/**",
  "**/test-results/**",
  "**/*.generated.ts",
  "supabase/functions/**", // Deno runtime: different globals and URL imports.
  // Build output that lands in the source tree. Generated by Next and by
  // @serwist/next respectively, gitignored, and not ours to style.
  "**/next-env.d.ts",
  "**/public/sw.js",
  "**/public/sw.js.map",
  "**/public/swe-worker-*.js",
]

/**
 * Shared flat config. Exported as an array so apps can spread it and append
 * their own overrides without re-deriving the base.
 */
export const acadigmaEslintConfig = [
  { ignores: IGNORED },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ["**/*.{js,mjs,ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.node, ...globals.browser },
    },
    plugins: { import: importPlugin },
    // No `import/resolver` is configured on purpose. The only import rules here are
    // ordering and duplicate detection, which work on specifiers alone; wiring the
    // TypeScript resolver would make every lint run re-resolve tsconfig `extends`
    // chains through pnpm's symlink farm for no benefit.
    rules: {
      // Import hygiene. Order is autofixable, so it never blocks a review.
      "import/order": [
        "error",
        {
          groups: [
            "builtin",
            "external",
            "internal",
            "parent",
            "sibling",
            "index",
            "type",
          ],
          pathGroups: [
            { pattern: "react", group: "external", position: "before" },
            { pattern: "next/**", group: "external", position: "before" },
            { pattern: "@acadigma/**", group: "internal" },
            { pattern: "@/**", group: "internal", position: "after" },
          ],
          pathGroupsExcludedImportTypes: ["react"],
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true },
        },
      ],
      "import/no-duplicates": "error",
      "import/first": "error",

      // Unused code is dead code; `_`-prefixed names are the documented escape hatch.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "no-console": ["warn", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "smart"],
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["../../packages/*"],
              message:
                "Import workspace packages by name (@acadigma/…), not by relative path.",
            },
          ],
        },
      ],
    },
  },

  // React / Next.js surface.
  {
    files: ["**/*.tsx", "apps/web/**/*.ts"],
    plugins: { "react-hooks": reactHooks, "@next/next": nextPlugin },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
      // App Router only: there is no `pages/` directory for this rule to check,
      // and leaving it on makes the plugin warn about its absence on every run.
      "@next/next/no-html-link-for-pages": "off",
    },
  },

  // Config and script files run in Node and may reach for the console.
  {
    files: ["**/*.config.{js,mjs,ts}", "scripts/**/*.mjs", "**/*.workspace.ts"],
    rules: { "no-console": "off" },
  },
]

export default acadigmaEslintConfig
